<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE groups [
	<!ELEMENT groups (dependencies)>
	<!ELEMENT dependencies (group+)>
	<!ELEMENT group EMPTY>
	<!ATTLIST group name NMTOKEN #REQUIRED>
	<!ATTLIST group depends-on NMTOKEN #REQUIRED>
]>

<groups>
	<dependencies>
		<group name="cookies" depends-on="openbrowser"></group>
		<group name="familiasRestaurante" depends-on="cookies"></group>
		<group name="paginaLogin" depends-on="familiasRestaurante"></group>
		<group name="loginCliente" depends-on="paginaLogin"></group>
		<group name="carrito" depends-on="loginCliente"></group>
		<group name="checkOut" depends-on="carrito"></group>
		<group name="checkPedidoDB" depends-on="checkOut"></group>
	</dependencies>
</groups>